indexSymbolForYfinance = {"Nifty 50" : "^NSEI",
          "Nifty Bank": "^NSEBANK"}


indexSymbolForNSE = {'Nifty 50': 'NIFTY',
                    'Financial Services': 'FINNIFTY',
                    'Nifty Bank': 'BANKNIFTY'}

# stocksSymbolForNSE = ['symbol': 'COALINDIA',
#                       'symbol': 'TCS',
#                       'symbol': 'RELIANCE',
#                       'symbol': 'IOC',
#                       'symbol': 'ITC',
#                       'symbol': 'BHEL',
#                       'symbol': 'SBIN'}]

stocks ={'Gujarat_Gas_Co_Ltd':	'GUJGASLTD',
'Aarti_Industries_Ltd':	'AARTIIND',
'ACC_Ltd':	'ACC',
'Adani_Enterprises_Ltd':	'ADANIENT',
'Adani_Ports_&_Special_Economic_Zone_Ltd':	'ADANIPORTS',
'Aditya_Birla_Fashion_and_Retail_Ltd':	'ABFRL',
'Alembic_Pharmaceuticals_Ltd':	'APLLTD',
'Alkem_Laboratories_Ltd':	'ALKEM',
'Amara_Raja_Batteries_Ltd':	'AMARAJABAT',
'Ambuja_Cements_Ltd':	'AMBUJACEM',
'Apollo_Hospitals_Enterprises_Ltd':	'APOLLOHOSP',
'Apollo_Tyres_Ltd':	'APOLLOTYRE',
'Ashok_Leyland_Ltd':	'ASHOKLEY',
'Asian_Paints_Ltd':	'ASIANPAINT',
'Astral_Ltd':	'ASTRAL',
'Au_Small_Finance_Bank_Ltd':	'AUBANK',
'Aurobindo_Pharma_Ltd':	'AUROPHARMA',
'Axis_Bank_Ltd':	'AXISBANK',
'Bajaj_Auto_Ltd':	'BAJAJ-AUTO',
'Bajaj_Finance':	'BAJFINANCE',
'Bajaj_Finserv_Ltd':	'BAJAJFINSV',
'Balkrishna_Industries_Ltd':	'BALKRISIND',
'Bandhan_Bank_Ltd':	'BANDHANBNK',
'Bank_of_Baroda':	'BANKBARODA',
'Bata_India_Ltd':	'BATAINDIA',
'Berger_Paints_India_Ltd':	'BERGEPAINT',
'Bharat_Electronics_Ltd':	'BEL',
'Bharat_Forge_Ltd':	'BHARATFORG',
'Bharat_Heavy_Electricals_Ltd':	'BHEL',
'Bharat_Petroleum_Corporation_Ltd':	'BPCL',
'Bharti_Airtel_Ltd':	'BHARTIARTL',
'Biocon_Ltd':	'BIOCON',
'Bosch_Ltd':	'BOSCHLTD',
'Britannia_Industries_Ltd':	'BRITANNIA',
'Cadila_Healthcare_Ltd':	'CADILAHC',
'Canara_Bank':	'CANBK',
'Cholamandalam_Investment_and_Finance_Company':	'CHOLAFIN',
'Cipla_Ltd':	'CIPLA',
'City_Union_Bank_Ltd':	'CUB',
'Coal_India_Ltd':	'COALINDIA',
'Coforge_Ltd':	'COFORGE',
'Colgate_Palmolive_(India)_Ltd':	'COLPAL',
'Container_Corporation_of_India_Ltd':	'CONCOR',
'Coromandel_International_Ltd':	'COROMANDEL',
'Cummins_India_Ltd':	'CUMMINSIND',
'Dabur_India_Ltd':	'DABUR',
'Deepak_Nitrite':	'DEEPAKNTR',
'Divis_Laboratories_Ltd':	'DIVISLAB',
'DLF_Ltd':	'DLF',
'Dr_Lal_Pathlabs_Ltd':	'LALPATHLAB',
'Dr_Reddys_Laboratories_Ltd':	'DRREDDY',
'Eicher_Motors_Ltd':	'EICHERMOT',
'Escorts_Ltd':	'ESCORTS',
'Exide_Industries_Ltd':	'EXIDEIND',
'Federal_Bank_Ltd':	'FEDERALBNK',
'GAIL_(India)_Ltd':	'GAIL',
'Glenmark_Pharmaceuticals_Ltd':	'GLENMARK',
'GMR_Infrastructure_Ltd':	'GMRINFRA',
'Godrej_Consumer_Products_Ltd':	'GODREJCP',
'Godrej_Properties_Ltd':	'GODREJPROP',
'Granules_India':	'GRANULES',
'Grasim_Industries_Ltd':	'GRASIM',
'Havells_India_Ltd':	'HAVELLS',
'HCL_Technologies_Ltd':	'HCLTECH',
'HDFC_Asset_Management_Company_Ltd':	'HDFCAMC',
'HDFC_Bank_Ltd':	'HDFCBANK',
'HDFC_Life_Insurance_Company_Ltd':	'HDFCLIFE',
'Hero_MotoCorp_Ltd':	'HEROMOTOCO',
'Hindalco_Industries_Ltd':	'HINDALCO',
'Hindustan_Petroleum_Corporation_Ltd':	'HINDPETRO',
'Hindustan_Unilever_Ltd':	'HINDUNILVR',
'Housing_Development_Finance_Corporation_Ltd':	'HDFC',
'I_T_C_Ltd':	'ITC',
'ICICI_Bank_Ltd':	'ICICIBANK',
'ICICI_Lombard_General_Insurance_Company_Ltd':	'ICICIGI',
'ICICI_Prudential_Life_Insurance_Company':	'ICICIPRULI',
'IDFC_First_Bank_Ltd':	'IDFCFIRSTB',
'Indiabulls_Housing_Finance':	'IBULHSGFIN',
'Indian_Hotels_Co_Ltd':	'INDHOTEL',
'Indian_Oil_Corporation_Ltd':	'IOC',
'Indian_Railway_Catering_&_Tourism_Corp_Ltd':	'IRCTC',
'Indraprastha_Gas_Ltd':	'IGL',
'Indus_Towers_Ltd':	'INDUSTOWER',
'IndusInd_Bank_Ltd':	'INDUSINDBK',
'Info_Edge_(India)_Ltd':	'NAUKRI',
'Infosys_Ltd':	'INFY',
'Interglobe_Aviation':	'INDIGO',
'Jindal_Steel_&_Power_Ltd':	'JINDALSTEL',
'JSW_Steel_Ltd':	'JSWSTEEL',
'Jubliant_Foodworks_Limited':	'JUBLFOOD',
'Kotak_Mahindra_Bank_Ltd':	'KOTAKBANK',
'L&T_Finance_Holdings_Ltd':	'L&TFH',
'L&T_Technology_Services':	'LTTS',
'Larsen_&_Toubro_Infotech':	'LTI',
'Larsen_&_Toubro_Ltd':	'LT',
'LIC_Housing_Finance_Ltd':	'LICHSGFIN',
'Lupin_Ltd':	'LUPIN',
'Mahanagar_Gas_Ltd':	'MGL',
'Mahindra_&_Mahindra_Financial_Services_Ltd':	'M&MFIN',
'Mahindra_&_Mahindra_Ltd':	'M&M',
'Manappuram_Finance_Limited':	'MANAPPURAM',
'Marico_Ltd':	'MARICO',
'Maruti_Suzuki_India_Ltd':	'MARUTI',
'Max_Financial_Services_Ltd':	'MFSL',
'Metropolis_Healthcare_Ltd':	'METROPOLIS',
'MindTree_Ltd':	'MINDTREE',
'Motherson_Sumi_Systems_Ltd':	'MOTHERSUMI',
'MphasiS_Ltd':	'MPHASIS',
'MRF_Ltd':	'MRF',
'Muthoot_Finance':	'MUTHOOTFIN',
'National_Aluminium_Co_Ltd':	'NATIONALUM',
'Navin_Fluorine_International_Ltd':	'NAVINFLUOR',
'Nestle_India_Ltd':	'NESTLEIND',
'Nippon_Life_India_Asset_Management_Ltd':	'NAM-INDIA',
'NMDC_Ltd':	'NMDC',
'NTPC_Ltd':	'NTPC',
'Oil_&_Natural_Gas_Corporation_Ltd':	'ONGC',
'Page_Industries':	'PAGEIND',
'Petronet_LNG_Ltd':	'PETRONET',
'Pfizer_Ltd':	'PFIZER',
'PI_Industries_Limited':	'PIIND',
'Pidilite_Industries_Ltd':	'PIDILITIND',
'Piramal_Enterprises':	'PEL',
'Power_Finance_Corporation_Ltd':	'PFC',
'Power_Grid_Corporation_of_India_Ltd':	'POWERGRID',
'Punjab_National_Bank':	'PNB',
'PVR_Limited':	'PVR',
'RBL_Bank':	'RBLBANK',
'REC_Ltd':	'RECLTD',
'Reliance_Industries_Ltd':	'RELIANCE',
'SBI_Life_Insurance_Company_Ltd':	'SBILIFE',
'Shree_Cement_Ltd':	'SHREECEM',
'Shriram_Transport_Finance_Co_Ltd':	'SRTRANSFIN',
'Siemens_Ltd':	'SIEMENS',
'SRF_Ltd':	'SRF',
'State_Bank_of_India':	'SBIN',
'Steel_Authority_of_India_Ltd':	'SAIL',
'Strides_Arcolab_Ltd':	'STAR',
'Sun_Pharmaceutical_Industries_Ltd':	'SUNPHARMA',
'Sun_TV_Network_Ltd':	'SUNTV',
'Tata_Chemicals_Ltd':	'TATACHEM',
'Tata_Consultancy_Services_Ltd':	'TCS',
'Tata_Consumer_Products_Ltd':	'TATACONSUM',
'Tata_Motors_Ltd':	'TATAMOTORS',
'Tata_Power_Co_Ltd':	'TATAPOWER',
'Tata_Steel_Ltd':	'TATASTEEL',
'Tech_Mahindra_Ltd':	'TECHM',
'The_Ramco_Cements_Ltd':	'RAMCOCEM',
'Titan_Company_Ltd':	'TITAN',
'Torrent_Pharmaceuticals_Ltd':	'TORNTPHARM',
'Torrent_Power_Ltd':	'TORNTPOWER',
'Trent_Ltd':	'TRENT',
'TVS_Motor_Company_Ltd':	'TVSMOTOR',
'UltraTech_Cement_Ltd':	'ULTRACEMCO',
'United_Breweries_Ltd':	'UBL',
'United_Spirits_Ltd':	'MCDOWELL-N',
'UPL_Ltd':	'UPL',
'Vedanta_Ltd':	'VEDL',
'Vodafone_Idea_Ltd':	'IDEA',
'Voltas_Ltd':	'VOLTAS',
'Wipro_Ltd':	'WIPRO',
'Zee_Entertainment_Enterprises_Ltd':	'ZEEL'}


                      





NseOptionChainURL = "https://www.nseindia.com/option-chain"