indexSymbolForYfinance = {"Nifty 50" : "^NSEI",
          "Nifty Bank": "^NSEBANK"}

indexSymbolForNSE = {'Nifty 50': 'NIFTY',
                    'Nifty Bank': 'BANKNIFTY'}

from enum import Enum
class Mode (Enum):
    INTRADAY = 1
    POSITIONAL = 2

mode = Mode.INTRADAY
# mode = Mode.POSITIONAL

stocks = {
    "ABB": {
        "instrument_token": 3329,
        "exchange_token": "13",
        "tradingsymbol": "ABB",
        "name": "ABB INDIA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "ACC": {
        "instrument_token": 5633,
        "exchange_token": "22",
        "tradingsymbol": "ACC",
        "name": "ACC",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "AUBANK": {
        "instrument_token": 5436929,
        "exchange_token": "21238",
        "tradingsymbol": "AUBANK",
        "name": "AU SMALL FINANCE BANK",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "AARTIIND": {
        "instrument_token": 1793,
        "exchange_token": "7",
        "tradingsymbol": "AARTIIND",
        "name": "AARTI INDUSTRIES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "ABBOTINDIA": {
        "instrument_token": 4583169,
        "exchange_token": "17903",
        "tradingsymbol": "ABBOTINDIA",
        "name": "ABBOTT INDIA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "ADANIENT": {
        "instrument_token": 6401,
        "exchange_token": "25",
        "tradingsymbol": "ADANIENT",
        "name": "ADANI ENTERPRISES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "ADANIPORTS": {
        "instrument_token": 3861249,
        "exchange_token": "15083",
        "tradingsymbol": "ADANIPORTS",
        "name": "ADANI PORT & SEZ",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "ABCAPITAL": {
        "instrument_token": 5533185,
        "exchange_token": "21614",
        "tradingsymbol": "ABCAPITAL",
        "name": "ADITYA BIRLA CAPITAL",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "ABFRL": {
        "instrument_token": 7707649,
        "exchange_token": "30108",
        "tradingsymbol": "ABFRL",
        "name": "ADITYA BIRLA FASHION & RT",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "ALKEM": {
        "instrument_token": 2995969,
        "exchange_token": "11703",
        "tradingsymbol": "ALKEM",
        "name": "ALKEM LABORATORIES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "AMBUJACEM": {
        "instrument_token": 325121,
        "exchange_token": "1270",
        "tradingsymbol": "AMBUJACEM",
        "name": "AMBUJA CEMENTS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "APOLLOHOSP": {
        "instrument_token": 40193,
        "exchange_token": "157",
        "tradingsymbol": "APOLLOHOSP",
        "name": "APOLLO HOSPITALS ENTER. L",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "APOLLOTYRE": {
        "instrument_token": 41729,
        "exchange_token": "163",
        "tradingsymbol": "APOLLOTYRE",
        "name": "APOLLO TYRES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "ASHOKLEY": {
        "instrument_token": 54273,
        "exchange_token": "212",
        "tradingsymbol": "ASHOKLEY",
        "name": "ASHOK LEYLAND",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "ASIANPAINT": {
        "instrument_token": 60417,
        "exchange_token": "236",
        "tradingsymbol": "ASIANPAINT",
        "name": "ASIAN PAINTS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "ASTRAL": {
        "instrument_token": 3691009,
        "exchange_token": "14418",
        "tradingsymbol": "ASTRAL",
        "name": "ASTRAL",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "ATUL": {
        "instrument_token": 67329,
        "exchange_token": "263",
        "tradingsymbol": "ATUL",
        "name": "ATUL",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "AUROPHARMA": {
        "instrument_token": 70401,
        "exchange_token": "275",
        "tradingsymbol": "AUROPHARMA",
        "name": "AUROBINDO PHARMA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "AXISBANK": {
        "instrument_token": 1510401,
        "exchange_token": "5900",
        "tradingsymbol": "AXISBANK",
        "name": "AXIS BANK",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "BSOFT": {
        "instrument_token": 1790465,
        "exchange_token": "6994",
        "tradingsymbol": "BSOFT",
        "name": "BIRLASOFT",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "BAJAJ-AUTO": {
        "instrument_token": 4267265,
        "exchange_token": "16669",
        "tradingsymbol": "BAJAJ-AUTO",
        "name": "BAJAJ AUTO",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "BAJFINANCE": {
        "instrument_token": 81153,
        "exchange_token": "317",
        "tradingsymbol": "BAJFINANCE",
        "name": "BAJAJ FINANCE",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "BAJAJFINSV": {
        "instrument_token": 4268801,
        "exchange_token": "16675",
        "tradingsymbol": "BAJAJFINSV",
        "name": "BAJAJ FINSERV",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "BALKRISIND": {
        "instrument_token": 85761,
        "exchange_token": "335",
        "tradingsymbol": "BALKRISIND",
        "name": "BALKRISHNA IND.",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "BALRAMCHIN": {
        "instrument_token": 87297,
        "exchange_token": "341",
        "tradingsymbol": "BALRAMCHIN",
        "name": "BALRAMPUR CHINI MILLS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "BANDHANBNK": {
        "instrument_token": 579329,
        "exchange_token": "2263",
        "tradingsymbol": "BANDHANBNK",
        "name": "BANDHAN BANK",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "BANKBARODA": {
        "instrument_token": 1195009,
        "exchange_token": "4668",
        "tradingsymbol": "BANKBARODA",
        "name": "BANK OF BARODA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "BATAINDIA": {
        "instrument_token": 94977,
        "exchange_token": "371",
        "tradingsymbol": "BATAINDIA",
        "name": "BATA INDIA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "BERGEPAINT": {
        "instrument_token": 103425,
        "exchange_token": "404",
        "tradingsymbol": "BERGEPAINT",
        "name": "BERGER PAINTS (I)",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "BEL": {
        "instrument_token": 98049,
        "exchange_token": "383",
        "tradingsymbol": "BEL",
        "name": "BHARAT ELECTRONICS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "BHARATFORG": {
        "instrument_token": 108033,
        "exchange_token": "422",
        "tradingsymbol": "BHARATFORG",
        "name": "BHARAT FORGE",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "BHEL": {
        "instrument_token": 112129,
        "exchange_token": "438",
        "tradingsymbol": "BHEL",
        "name": "BHEL",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "BPCL": {
        "instrument_token": 134657,
        "exchange_token": "526",
        "tradingsymbol": "BPCL",
        "name": "BHARAT PETROLEUM CORP  LT",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "BHARTIARTL": {
        "instrument_token": 2714625,
        "exchange_token": "10604",
        "tradingsymbol": "BHARTIARTL",
        "name": "BHARTI AIRTEL",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "BIOCON": {
        "instrument_token": 2911489,
        "exchange_token": "11373",
        "tradingsymbol": "BIOCON",
        "name": "BIOCON",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "BOSCHLTD": {
        "instrument_token": 558337,
        "exchange_token": "2181",
        "tradingsymbol": "BOSCHLTD",
        "name": "BOSCH",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "BRITANNIA": {
        "instrument_token": 140033,
        "exchange_token": "547",
        "tradingsymbol": "BRITANNIA",
        "name": "BRITANNIA INDUSTRIES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "CANFINHOME": {
        "instrument_token": 149249,
        "exchange_token": "583",
        "tradingsymbol": "CANFINHOME",
        "name": "CAN FIN HOMES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "CANBK": {
        "instrument_token": 2763265,
        "exchange_token": "10794",
        "tradingsymbol": "CANBK",
        "name": "CANARA BANK",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "CHAMBLFERT": {
        "instrument_token": 163073,
        "exchange_token": "637",
        "tradingsymbol": "CHAMBLFERT",
        "name": "CHAMBAL FERTILIZERS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "CHOLAFIN": {
        "instrument_token": 175361,
        "exchange_token": "685",
        "tradingsymbol": "CHOLAFIN",
        "name": "CHOLAMANDALAM IN & FIN CO",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "CIPLA": {
        "instrument_token": 177665,
        "exchange_token": "694",
        "tradingsymbol": "CIPLA",
        "name": "CIPLA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "CUB": {
        "instrument_token": 1459457,
        "exchange_token": "5701",
        "tradingsymbol": "CUB",
        "name": "CITY UNION BANK",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "COALINDIA": {
        "instrument_token": 5215745,
        "exchange_token": "20374",
        "tradingsymbol": "COALINDIA",
        "name": "COAL INDIA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "COFORGE": {
        "instrument_token": 2955009,
        "exchange_token": "11543",
        "tradingsymbol": "COFORGE",
        "name": "COFORGE",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "COLPAL": {
        "instrument_token": 3876097,
        "exchange_token": "15141",
        "tradingsymbol": "COLPAL",
        "name": "COLGATE PALMOLIVE",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "CONCOR": {
        "instrument_token": 1215745,
        "exchange_token": "4749",
        "tradingsymbol": "CONCOR",
        "name": "CONTAINER CORP OF IND",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "COROMANDEL": {
        "instrument_token": 189185,
        "exchange_token": "739",
        "tradingsymbol": "COROMANDEL",
        "name": "COROMANDEL INTERNTL.",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "CROMPTON": {
        "instrument_token": 4376065,
        "exchange_token": "17094",
        "tradingsymbol": "CROMPTON",
        "name": "CROMPT GREA CON ELEC",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "CUMMINSIND": {
        "instrument_token": 486657,
        "exchange_token": "1901",
        "tradingsymbol": "CUMMINSIND",
        "name": "CUMMINS INDIA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "DLF": {
        "instrument_token": 3771393,
        "exchange_token": "14732",
        "tradingsymbol": "DLF",
        "name": "DLF",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "DABUR": {
        "instrument_token": 197633,
        "exchange_token": "772",
        "tradingsymbol": "DABUR",
        "name": "DABUR INDIA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "DALBHARAT": {
        "instrument_token": 2067201,
        "exchange_token": "8075",
        "tradingsymbol": "DALBHARAT",
        "name": "DALMIA BHARAT",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "DEEPAKNTR": {
        "instrument_token": 5105409,
        "exchange_token": "19943",
        "tradingsymbol": "DEEPAKNTR",
        "name": "DEEPAK NITRITE",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "DIVISLAB": {
        "instrument_token": 2800641,
        "exchange_token": "10940",
        "tradingsymbol": "DIVISLAB",
        "name": "DIVI S LABORATORIES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "DIXON": {
        "instrument_token": 5552641,
        "exchange_token": "21690",
        "tradingsymbol": "DIXON",
        "name": "DIXON TECHNO (INDIA)",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "LALPATHLAB": {
        "instrument_token": 2983425,
        "exchange_token": "11654",
        "tradingsymbol": "LALPATHLAB",
        "name": "DR. LAL PATH LABS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "DRREDDY": {
        "instrument_token": 225537,
        "exchange_token": "881",
        "tradingsymbol": "DRREDDY",
        "name": "DR. REDDY S LABORATORIES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "EICHERMOT": {
        "instrument_token": 232961,
        "exchange_token": "910",
        "tradingsymbol": "EICHERMOT",
        "name": "EICHER MOTORS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "ESCORTS": {
        "instrument_token": 245249,
        "exchange_token": "958",
        "tradingsymbol": "ESCORTS",
        "name": "ESCORTS KUBOTA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "EXIDEIND": {
        "instrument_token": 173057,
        "exchange_token": "676",
        "tradingsymbol": "EXIDEIND",
        "name": "EXIDE INDUSTRIES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "GAIL": {
        "instrument_token": 1207553,
        "exchange_token": "4717",
        "tradingsymbol": "GAIL",
        "name": "GAIL (INDIA)",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "GMRINFRA": {
        "instrument_token": 3463169,
        "exchange_token": "13528",
        "tradingsymbol": "GMRINFRA",
        "name": "GMR AIRPORTS INFRA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "GLENMARK": {
        "instrument_token": 1895937,
        "exchange_token": "7406",
        "tradingsymbol": "GLENMARK",
        "name": "GLENMARK PHARMACEUTICALS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "GODREJCP": {
        "instrument_token": 2585345,
        "exchange_token": "10099",
        "tradingsymbol": "GODREJCP",
        "name": "GODREJ CONSUMER PRODUCTS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "GODREJPROP": {
        "instrument_token": 4576001,
        "exchange_token": "17875",
        "tradingsymbol": "GODREJPROP",
        "name": "GODREJ PROPERTIES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "GRANULES": {
        "instrument_token": 3039233,
        "exchange_token": "11872",
        "tradingsymbol": "GRANULES",
        "name": "GRANULES INDIA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "GRASIM": {
        "instrument_token": 315393,
        "exchange_token": "1232",
        "tradingsymbol": "GRASIM",
        "name": "GRASIM INDUSTRIES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "GUJGASLTD": {
        "instrument_token": 2713345,
        "exchange_token": "10599",
        "tradingsymbol": "GUJGASLTD",
        "name": "GUJARAT GAS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "GNFC": {
        "instrument_token": 300545,
        "exchange_token": "1174",
        "tradingsymbol": "GNFC",
        "name": "GUJ NAR VAL FER & CHEM L",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "HCLTECH": {
        "instrument_token": 1850625,
        "exchange_token": "7229",
        "tradingsymbol": "HCLTECH",
        "name": "HCL TECHNOLOGIES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "HDFCAMC": {
        "instrument_token": 1086465,
        "exchange_token": "4244",
        "tradingsymbol": "HDFCAMC",
        "name": "HDFC AMC",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "HDFCBANK": {
        "instrument_token": 341249,
        "exchange_token": "1333",
        "tradingsymbol": "HDFCBANK",
        "name": "HDFC BANK",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "HDFCLIFE": {
        "instrument_token": 119553,
        "exchange_token": "467",
        "tradingsymbol": "HDFCLIFE",
        "name": "HDFC LIFE INS CO",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "HAVELLS": {
        "instrument_token": 2513665,
        "exchange_token": "9819",
        "tradingsymbol": "HAVELLS",
        "name": "HAVELLS INDIA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "HEROMOTOCO": {
        "instrument_token": 345089,
        "exchange_token": "1348",
        "tradingsymbol": "HEROMOTOCO",
        "name": "HERO MOTOCORP",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "HINDALCO": {
        "instrument_token": 348929,
        "exchange_token": "1363",
        "tradingsymbol": "HINDALCO",
        "name": "HINDALCO  INDUSTRIES ",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "HAL": {
        "instrument_token": 589569,
        "exchange_token": "2303",
        "tradingsymbol": "HAL",
        "name": "HINDUSTAN AERONAUTICS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "HINDCOPPER": {
        "instrument_token": 4592385,
        "exchange_token": "17939",
        "tradingsymbol": "HINDCOPPER",
        "name": "HINDUSTAN COPPER",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "HINDPETRO": {
        "instrument_token": 359937,
        "exchange_token": "1406",
        "tradingsymbol": "HINDPETRO",
        "name": "HINDUSTAN PETROLEUM CORP",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "HINDUNILVR": {
        "instrument_token": 356865,
        "exchange_token": "1394",
        "tradingsymbol": "HINDUNILVR",
        "name": "HINDUSTAN UNILEVER",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "ICICIBANK": {
        "instrument_token": 1270529,
        "exchange_token": "4963",
        "tradingsymbol": "ICICIBANK",
        "name": "ICICI BANK",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "ICICIGI": {
        "instrument_token": 5573121,
        "exchange_token": "21770",
        "tradingsymbol": "ICICIGI",
        "name": "ICICI LOMBARD GIC",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "ICICIPRULI": {
        "instrument_token": 4774913,
        "exchange_token": "18652",
        "tradingsymbol": "ICICIPRULI",
        "name": "ICICI PRU LIFE INS CO",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "IDFCFIRSTB": {
        "instrument_token": 2863105,
        "exchange_token": "11184",
        "tradingsymbol": "IDFCFIRSTB",
        "name": "IDFC FIRST BANK",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "IDFC": {
        "instrument_token": 3060993,
        "exchange_token": "11957",
        "tradingsymbol": "IDFC",
        "name": "IDFC",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "IPCALAB": {
        "instrument_token": 418049,
        "exchange_token": "1633",
        "tradingsymbol": "IPCALAB",
        "name": "IPCA LABORATORIES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "ITC": {
        "instrument_token": 424961,
        "exchange_token": "1660",
        "tradingsymbol": "ITC",
        "name": "ITC",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "INDIAMART": {
        "instrument_token": 2745857,
        "exchange_token": "10726",
        "tradingsymbol": "INDIAMART",
        "name": "INDIAMART INTERMESH",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "IEX": {
        "instrument_token": 56321,
        "exchange_token": "220",
        "tradingsymbol": "IEX",
        "name": "INDIAN ENERGY EXC",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "IOC": {
        "instrument_token": 415745,
        "exchange_token": "1624",
        "tradingsymbol": "IOC",
        "name": "INDIAN OIL CORP",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "IRCTC": {
        "instrument_token": 3484417,
        "exchange_token": "13611",
        "tradingsymbol": "IRCTC",
        "name": "INDIAN RAIL TOUR CORP",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "IGL": {
        "instrument_token": 2883073,
        "exchange_token": "11262",
        "tradingsymbol": "IGL",
        "name": "INDRAPRASTHA GAS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "INDUSTOWER": {
        "instrument_token": 7458561,
        "exchange_token": "29135",
        "tradingsymbol": "INDUSTOWER",
        "name": "INDUS TOWERS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "INDUSINDBK": {
        "instrument_token": 1346049,
        "exchange_token": "5258",
        "tradingsymbol": "INDUSINDBK",
        "name": "INDUSIND BANK",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "NAUKRI": {
        "instrument_token": 3520257,
        "exchange_token": "13751",
        "tradingsymbol": "NAUKRI",
        "name": "INFO EDGE (I)",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "INFY": {
        "instrument_token": 408065,
        "exchange_token": "1594",
        "tradingsymbol": "INFY",
        "name": "INFOSYS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "INDIGO": {
        "instrument_token": 2865921,
        "exchange_token": "11195",
        "tradingsymbol": "INDIGO",
        "name": "INTERGLOBE AVIATION",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "JKCEMENT": {
        "instrument_token": 3397121,
        "exchange_token": "13270",
        "tradingsymbol": "JKCEMENT",
        "name": "JK CEMENT",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "JSWSTEEL": {
        "instrument_token": 3001089,
        "exchange_token": "11723",
        "tradingsymbol": "JSWSTEEL",
        "name": "JSW STEEL",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "JINDALSTEL": {
        "instrument_token": 1723649,
        "exchange_token": "6733",
        "tradingsymbol": "JINDALSTEL",
        "name": "JINDAL STEEL & POWER",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "JUBLFOOD": {
        "instrument_token": 4632577,
        "exchange_token": "18096",
        "tradingsymbol": "JUBLFOOD",
        "name": "JUBILANT FOODWORKS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "KOTAKBANK": {
        "instrument_token": 492033,
        "exchange_token": "1922",
        "tradingsymbol": "KOTAKBANK",
        "name": "KOTAK MAHINDRA BANK",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "LTF": {
        "instrument_token": 6386689,
        "exchange_token": "24948",
        "tradingsymbol": "LTF",
        "name": "L&T FINANCE",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "LTTS": {
        "instrument_token": 4752385,
        "exchange_token": "18564",
        "tradingsymbol": "LTTS",
        "name": "L&T TECHNOLOGY SER.",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "LICHSGFIN": {
        "instrument_token": 511233,
        "exchange_token": "1997",
        "tradingsymbol": "LICHSGFIN",
        "name": "LIC HOUSING FINANCE",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "LTIM": {
        "instrument_token": 4561409,
        "exchange_token": "17818",
        "tradingsymbol": "LTIM",
        "name": "LTIMINDTREE",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "LT": {
        "instrument_token": 2939649,
        "exchange_token": "11483",
        "tradingsymbol": "LT",
        "name": "LARSEN & TOUBRO",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "LAURUSLABS": {
        "instrument_token": 4923905,
        "exchange_token": "19234",
        "tradingsymbol": "LAURUSLABS",
        "name": "LAURUS LABS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "LUPIN": {
        "instrument_token": 2672641,
        "exchange_token": "10440",
        "tradingsymbol": "LUPIN",
        "name": "LUPIN",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "MRF": {
        "instrument_token": 582913,
        "exchange_token": "2277",
        "tradingsymbol": "MRF",
        "name": "MRF",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "MGL": {
        "instrument_token": 4488705,
        "exchange_token": "17534",
        "tradingsymbol": "MGL",
        "name": "MAHANAGAR GAS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "M&MFIN": {
        "instrument_token": 3400961,
        "exchange_token": "13285",
        "tradingsymbol": "M&MFIN",
        "name": "M&M FIN. SERVICES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "M&M": {
        "instrument_token": 519937,
        "exchange_token": "2031",
        "tradingsymbol": "M&M",
        "name": "MAHINDRA & MAHINDRA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "MANAPPURAM": {
        "instrument_token": 4879617,
        "exchange_token": "19061",
        "tradingsymbol": "MANAPPURAM",
        "name": "MANAPPURAM FINANCE",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "MARICO": {
        "instrument_token": 1041153,
        "exchange_token": "4067",
        "tradingsymbol": "MARICO",
        "name": "MARICO",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "MARUTI": {
        "instrument_token": 2815745,
        "exchange_token": "10999",
        "tradingsymbol": "MARUTI",
        "name": "MARUTI SUZUKI INDIA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "MFSL": {
        "instrument_token": 548353,
        "exchange_token": "2142",
        "tradingsymbol": "MFSL",
        "name": "MAX FINANCIAL SERV",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "METROPOLIS": {
        "instrument_token": 2452737,
        "exchange_token": "9581",
        "tradingsymbol": "METROPOLIS",
        "name": "METROPOLIS HEALTHCARE",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "MPHASIS": {
        "instrument_token": 1152769,
        "exchange_token": "4503",
        "tradingsymbol": "MPHASIS",
        "name": "MPHASIS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "MCX": {
        "instrument_token": 7982337,
        "exchange_token": "31181",
        "tradingsymbol": "MCX",
        "name": "MULTI COMMODITY EXCHANGE",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "MUTHOOTFIN": {
        "instrument_token": 6054401,
        "exchange_token": "23650",
        "tradingsymbol": "MUTHOOTFIN",
        "name": "MUTHOOT FINANCE",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "NMDC": {
        "instrument_token": 3924993,
        "exchange_token": "15332",
        "tradingsymbol": "NMDC",
        "name": "NMDC",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "NTPC": {
        "instrument_token": 2977281,
        "exchange_token": "11630",
        "tradingsymbol": "NTPC",
        "name": "NTPC",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "NATIONALUM": {
        "instrument_token": 1629185,
        "exchange_token": "6364",
        "tradingsymbol": "NATIONALUM",
        "name": "NATIONAL ALUMINIUM CO",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "NAVINFLUOR": {
        "instrument_token": 3756033,
        "exchange_token": "14672",
        "tradingsymbol": "NAVINFLUOR",
        "name": "NAVIN FLUORINE INT.",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "NESTLEIND": {
        "instrument_token": 4598529,
        "exchange_token": "17963",
        "tradingsymbol": "NESTLEIND",
        "name": "NESTLE INDIA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "OBEROIRLTY": {
        "instrument_token": 5181953,
        "exchange_token": "20242",
        "tradingsymbol": "OBEROIRLTY",
        "name": "OBEROI REALTY",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "ONGC": {
        "instrument_token": 633601,
        "exchange_token": "2475",
        "tradingsymbol": "ONGC",
        "name": "OIL AND NATURAL GAS CORP.",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "OFSS": {
        "instrument_token": 2748929,
        "exchange_token": "10738",
        "tradingsymbol": "OFSS",
        "name": "ORACLE FIN SERV SOFT",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "PIIND": {
        "instrument_token": 6191105,
        "exchange_token": "24184",
        "tradingsymbol": "PIIND",
        "name": "PI INDUSTRIES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "PVRINOX": {
        "instrument_token": 3365633,
        "exchange_token": "13147",
        "tradingsymbol": "PVRINOX",
        "name": "PVR INOX",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "PAGEIND": {
        "instrument_token": 3689729,
        "exchange_token": "14413",
        "tradingsymbol": "PAGEIND",
        "name": "PAGE INDUSTRIES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "PERSISTENT": {
        "instrument_token": 4701441,
        "exchange_token": "18365",
        "tradingsymbol": "PERSISTENT",
        "name": "PERSISTENT SYSTEMS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "PETRONET": {
        "instrument_token": 2905857,
        "exchange_token": "11351",
        "tradingsymbol": "PETRONET",
        "name": "PETRONET LNG",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "PIDILITIND": {
        "instrument_token": 681985,
        "exchange_token": "2664",
        "tradingsymbol": "PIDILITIND",
        "name": "PIDILITE INDUSTRIES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "PEL": {
        "instrument_token": 617473,
        "exchange_token": "2412",
        "tradingsymbol": "PEL",
        "name": "PIRAMAL ENTERPRISES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "POLYCAB": {
        "instrument_token": 2455041,
        "exchange_token": "9590",
        "tradingsymbol": "POLYCAB",
        "name": "POLYCAB INDIA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "PFC": {
        "instrument_token": 3660545,
        "exchange_token": "14299",
        "tradingsymbol": "PFC",
        "name": "POWER FIN CORP",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "POWERGRID": {
        "instrument_token": 3834113,
        "exchange_token": "14977",
        "tradingsymbol": "POWERGRID",
        "name": "POWER GRID CORP.",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "PNB": {
        "instrument_token": 2730497,
        "exchange_token": "10666",
        "tradingsymbol": "PNB",
        "name": "PUNJAB NATIONAL BANK",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "RBLBANK": {
        "instrument_token": 4708097,
        "exchange_token": "18391",
        "tradingsymbol": "RBLBANK",
        "name": "RBL BANK",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "RECLTD": {
        "instrument_token": 3930881,
        "exchange_token": "15355",
        "tradingsymbol": "RECLTD",
        "name": "REC",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "RELIANCE": {
        "instrument_token": 738561,
        "exchange_token": "2885",
        "tradingsymbol": "RELIANCE",
        "name": "RELIANCE INDUSTRIES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "SBICARD": {
        "instrument_token": 4600577,
        "exchange_token": "17971",
        "tradingsymbol": "SBICARD",
        "name": "SBI CARDS & PAY SER",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "SBILIFE": {
        "instrument_token": 5582849,
        "exchange_token": "21808",
        "tradingsymbol": "SBILIFE",
        "name": "SBI LIFE INSURANCE CO",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "SHREECEM": {
        "instrument_token": 794369,
        "exchange_token": "3103",
        "tradingsymbol": "SHREECEM",
        "name": "SHREE CEMENT",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "SRF": {
        "instrument_token": 837889,
        "exchange_token": "3273",
        "tradingsymbol": "SRF",
        "name": "SRF",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "MOTHERSON": {
        "instrument_token": 1076225,
        "exchange_token": "4204",
        "tradingsymbol": "MOTHERSON",
        "name": "SAMVRDHNA MTHRSN INTL",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "SHRIRAMFIN": {
        "instrument_token": 1102337,
        "exchange_token": "4306",
        "tradingsymbol": "SHRIRAMFIN",
        "name": "SHRIRAM FINANCE",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "SIEMENS": {
        "instrument_token": 806401,
        "exchange_token": "3150",
        "tradingsymbol": "SIEMENS",
        "name": "SIEMENS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "SBIN": {
        "instrument_token": 779521,
        "exchange_token": "3045",
        "tradingsymbol": "SBIN",
        "name": "STATE BANK OF INDIA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "SAIL": {
        "instrument_token": 758529,
        "exchange_token": "2963",
        "tradingsymbol": "SAIL",
        "name": "STEEL AUTHORITY OF INDIA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "SUNPHARMA": {
        "instrument_token": 857857,
        "exchange_token": "3351",
        "tradingsymbol": "SUNPHARMA",
        "name": "SUN PHARMACEUTICAL IND L",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "SUNTV": {
        "instrument_token": 3431425,
        "exchange_token": "13404",
        "tradingsymbol": "SUNTV",
        "name": "SUN TV NETWORK",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "SYNGENE": {
        "instrument_token": 2622209,
        "exchange_token": "10243",
        "tradingsymbol": "SYNGENE",
        "name": "SYNGENE INTERNATIONAL",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "TATACONSUM": {
        "instrument_token": 878593,
        "exchange_token": "3432",
        "tradingsymbol": "TATACONSUM",
        "name": "TATA CONSUMER PRODUCT",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "TVSMOTOR": {
        "instrument_token": 2170625,
        "exchange_token": "8479",
        "tradingsymbol": "TVSMOTOR",
        "name": "TVS MOTOR COMPANY ",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "TATACHEM": {
        "instrument_token": 871681,
        "exchange_token": "3405",
        "tradingsymbol": "TATACHEM",
        "name": "TATA CHEMICALS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "TATACOMM": {
        "instrument_token": 952577,
        "exchange_token": "3721",
        "tradingsymbol": "TATACOMM",
        "name": "TATA COMMUNICATIONS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "TCS": {
        "instrument_token": 2953217,
        "exchange_token": "11536",
        "tradingsymbol": "TCS",
        "name": "TATA CONSULTANCY SERV LT",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "TATAMOTORS": {
        "instrument_token": 884737,
        "exchange_token": "3456",
        "tradingsymbol": "TATAMOTORS",
        "name": "TATA MOTORS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "TATAPOWER": {
        "instrument_token": 877057,
        "exchange_token": "3426",
        "tradingsymbol": "TATAPOWER",
        "name": "TATA POWER CO",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "TATASTEEL": {
        "instrument_token": 895745,
        "exchange_token": "3499",
        "tradingsymbol": "TATASTEEL",
        "name": "TATA STEEL",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "TECHM": {
        "instrument_token": 3465729,
        "exchange_token": "13538",
        "tradingsymbol": "TECHM",
        "name": "TECH MAHINDRA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "FEDERALBNK": {
        "instrument_token": 261889,
        "exchange_token": "1023",
        "tradingsymbol": "FEDERALBNK",
        "name": "FEDERAL BANK",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "INDIACEM": {
        "instrument_token": 387841,
        "exchange_token": "1515",
        "tradingsymbol": "INDIACEM",
        "name": "THE INDIA CEMENTS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "INDHOTEL": {
        "instrument_token": 387073,
        "exchange_token": "1512",
        "tradingsymbol": "INDHOTEL",
        "name": "THE INDIAN HOTELS CO.",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "RAMCOCEM": {
        "instrument_token": 523009,
        "exchange_token": "2043",
        "tradingsymbol": "RAMCOCEM",
        "name": "THE RAMCO CEMENTS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "TITAN": {
        "instrument_token": 897537,
        "exchange_token": "3506",
        "tradingsymbol": "TITAN",
        "name": "TITAN COMPANY",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "TORNTPHARM": {
        "instrument_token": 900609,
        "exchange_token": "3518",
        "tradingsymbol": "TORNTPHARM",
        "name": "TORRENT PHARMACEUTICALS L",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "TRENT": {
        "instrument_token": 502785,
        "exchange_token": "1964",
        "tradingsymbol": "TRENT",
        "name": "TRENT",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "UPL": {
        "instrument_token": 2889473,
        "exchange_token": "11287",
        "tradingsymbol": "UPL",
        "name": "UPL",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "ULTRACEMCO": {
        "instrument_token": 2952193,
        "exchange_token": "11532",
        "tradingsymbol": "ULTRACEMCO",
        "name": "ULTRATECH CEMENT",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "UBL": {
        "instrument_token": 4278529,
        "exchange_token": "16713",
        "tradingsymbol": "UBL",
        "name": "UNITED BREWERIES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "VEDL": {
        "instrument_token": 784129,
        "exchange_token": "3063",
        "tradingsymbol": "VEDL",
        "name": "VEDANTA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "IDEA": {
        "instrument_token": 3677697,
        "exchange_token": "14366",
        "tradingsymbol": "IDEA",
        "name": "VODAFONE IDEA",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.01,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "VOLTAS": {
        "instrument_token": 951809,
        "exchange_token": "3718",
        "tradingsymbol": "VOLTAS",
        "name": "VOLTAS",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "WIPRO": {
        "instrument_token": 969473,
        "exchange_token": "3787",
        "tradingsymbol": "WIPRO",
        "name": "WIPRO",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    },
    "ZYDUSLIFE": {
        "instrument_token": 2029825,
        "exchange_token": "7929",
        "tradingsymbol": "ZYDUSLIFE",
        "name": "ZYDUS LIFESCIENCES",
        "last_price": 0.0,
        "expiry": "",
        "strike": 0.0,
        "tick_size": 0.05,
        "lot_size": 1,
        "instrument_type": "EQ",
        "segment": "NSE",
        "exchange": "NSE"
    }
}


NseOptionChainURL = "https://www.nseindia.com/option-chain"


# Opstra Data Collection Constants
OpstraURLs = {"TickerURL" : "https://opstra.definedge.com/api/tickers",
            "MonthlyExpiryURL" : "https://opstra.definedge.com/api/monthlies",
            "WeeklyExpiryURL" : "https://opstra.definedge.com/api/weeklies",
            "IVChartURL": "https://opstra.definedge.com/api/ivcharts/{}",
            "FII_DII_DATA_URL": "https://opstra.definedge.com/api/fiidiidata"}






